##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "./plugins/netlify-plugin-lerna-cache"
  # Plugin configuration
  #  [plugins.inputs]
  #  foo = "bar"

[build]
# Dummy build command
command = "lerna bootstrap && lerna run prepare --scope $(cat .changed_scope)"
